name: Deploy Frontend to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Deploy via rsync
        uses: scottbrenner/rsync-deploy-github-action@v1
        with:
          args: '-avz --delete'
          source: './frontend/dist/'
          destination: 'ilya@${{ secrets.SERVER_IP }}:/home/ilya/cloud_storage/frontend/dist'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    


